dist: trusty
language: python
python:
    - "3.5"
install:
    - "deactivate"
    - "make setup PYTHON=/opt/python/3.5/bin/python"
    - "bin/pip install coveralls"
script: "make coverage"
after_success: "bin/coveralls"
